# 
# This is a Dockerfile for DEBIAN-DEV-BASE
#

FROM ierturk/debian-dev-qt:latest

ARG DEBIAN_FRONTEND=noninteractive

#
# Tools
#

# RUN apt-get update && \
#     apt-get install -y --no-install-recommends openssh-server && \
#     rm -rf /var/lib/apt/lists/* && \
#     apt-get clean
# 
# RUN ssh-keygen -A && mkdir -p /run/sshd